# Generated by Django 5.1.7 on 2025-03-30 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualHerbalPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(help_text='The botanical name of the plant (e.g., Ocimum tenuiflorum)', max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('common_names', models.JSONField(default=list, help_text="List of common names for the plant (e.g., ['Tulsi', 'Holy Basil'])")),
                ('medicinal_uses', models.TextField(help_text='AYUSH-approved medicinal uses of the plant')),
                ('cultivation_guide', models.TextField(help_text='Detailed cultivation instructions')),
                ('ayush_certified', models.BooleanField(default=False, help_text='Whether the plant is AYUSH certified')),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='Cultivation difficulty level', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Virtual Herbal Plant',
                'verbose_name_plural': 'Virtual Herbal Plants',
                'ordering': ['scientific_name'],
                'indexes': [models.Index(fields=['scientific_name'], name='api_virtual_scienti_e2e871_idx'), models.Index(fields=['ayush_certified'], name='api_virtual_ayush_c_372f52_idx')],
            },
        ),
    ]
